name: Pull Request Diff Analysis

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  analyze-pr-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get PR changes
        id: pr-diff
        run: |
          # Store the changes in a file
          echo "Changed files:" > pr_changes.txt
          git diff --name-status ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} >> pr_changes.txt
          echo "" >> pr_changes.txt
          echo "Detailed changes:" >> pr_changes.txt
          git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} >> pr_changes.txt
          
          # Store the content in an environment variable
          PR_CHANGES=$(cat pr_changes.txt)
          
          # Create a properly formatted output for GitHub Actions
          {
            echo 'PR_CHANGES<<EOF'
            echo "$PR_CHANGES"
            echo 'EOF'
          } >> $GITHUB_ENV
          
          # Also set as output
          echo "diff_content<<EOF" >> $GITHUB_OUTPUT
          echo "$PR_CHANGES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create PR Comment
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Pull Request Changes
            ```diff
            ${{ env.PR_CHANGES }}
            ```