name: Ollama DeepSeek Test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test-ollama:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | sh

      - name: Run DeepSeek model
        run: |
          echo "::group::Model Response"
          echo "Sending prompt to DeepSeek model..."
          echo "----------------------------------------"
          # Capture the response and clean it up
          response=$(echo "hello" | ollama run deepseek-r1:1.5b 2>/dev/null | grep -v '^[0-9]' | grep -v '25[hl]' | grep -v '⠙\|⠸\|⠴\|⠦\|⠧\|⠇\|⠏\|⠋\|⠙\|⠹\|⠼' | sed '/^$/d')
          echo "Model response:"
          echo "----------------------------------------"
          echo "$response" | sed 's/^/> /'
          echo "----------------------------------------"
          echo "::endgroup::"